title: Dossier Registratie
description: Maak het leven makkelijker met Dossier Registratie voor de Uitvaartverzorging
theme: just-the-docs

url: https://patrickst1991.github.io/Uitvaartverzorging-Dossier-Registratie/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
