remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dossier Registratie
description: Maakt het leven makkelijker door het simpel en effectief registreren van uitvaartverzorging data
