title: DigiGraf
description: Maakt het leven makkelijker door Dossier Registratie voor de Uitvaartverzorging.
theme: just-the-docs

url: https://patrickst1991.github.io/Uitvaartverzorging-Dossier-Registratie/

aux_links:
  Template Repository: https://patrickst1991.github.io/Uitvaartverzorging-Dossier-Registratie/
