remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Uitvaartverzorging Beheer Applicatie - Dossier Registratie
description: Maakt het leven makkelijker door het simpel en effectief registreren van uitvaartverzorging data
author: Patrick Stel
navigation:
  - title: "Start"
    url: /
  - title: "Installatie"
    url: /about
  - title: "Gebruik"
    url: /contact
  - title: "Beheer"
    url: /contact
